# Generated by Django 4.2.30 on 2026-09-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('MATCH', 'Match'), ('NO_MATCH', 'No Match')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('decided_by', models.CharField(max_length=100)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MATCHED_WITH_DIFFERENCES', 'Matched With Differences'), ('NEEDS_REVIEW', 'Needs Review'), ('UNMATCHED_OUR_SIDE', 'Unmatched Our Side'), ('UNMATCHED_EXTERNAL_SIDE', 'Unmatched External Side'), ('EXCLUDED', 'Excluded')], max_length=40)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('differences_json', models.JSONField(default=dict)),
                ('candidates_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('amount_tolerance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_tolerance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity_tolerance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('time_tolerance_seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('instrument', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_versions', to='reconciliation_app.file')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reconciliation_app.transaction')),
            ],
            options={
                'ordering': ['transaction_id', 'version_number'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_transactions', to='reconciliation_app.transactionversion'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reconciliation_app.source'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_ruleset_version'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='external_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_runs', to='reconciliation_app.file'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='our_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='our_runs', to='reconciliation_app.file'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reconciliation_app.ruleset'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='external_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_reconciliation_results', to='reconciliation_app.transactionversion'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='our_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_reconciliation_results', to='reconciliation_app.transactionversion'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconciliation_app.reconciliationrun'),
        ),
        migrations.AddField(
            model_name='manualdecision',
            name='external_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_external_decisions', to='reconciliation_app.transactionversion'),
        ),
        migrations.AddField(
            model_name='manualdecision',
            name='our_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_our_decisions', to='reconciliation_app.transactionversion'),
        ),
        migrations.AddField(
            model_name='manualdecision',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_decisions', to='reconciliation_app.reconciliationresult'),
        ),
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='reconciliation_app.source'),
        ),
        migrations.AddConstraint(
            model_name='transactionversion',
            constraint=models.UniqueConstraint(fields=('transaction', 'version_number'), name='unique_transaction_version'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('source', 'source_reference'), name='unique_source_reference'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationresult',
            constraint=models.UniqueConstraint(fields=('run', 'our_version'), name='unique_run_our_version'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationresult',
            constraint=models.UniqueConstraint(fields=('run', 'external_version'), name='unique_run_external_version'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('source', 'file_hash'), name='unique_source_file_hash'),
        ),
    ]
