# Generated by Django 4.2.30 on 2026-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationresult',
            name='differences_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='manualdecision',
            constraint=models.UniqueConstraint(fields=('our_version', 'external_version'), name='unique_manual_transaction_pair'),
        ),
    ]
