# Generated by Django 4.2.30 on 2026-09-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0002_alter_reconciliationresult_differences_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdecision',
            name='external_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_external_decisions', to='reconciliation_app.transaction'),
        ),
        migrations.AddField(
            model_name='manualdecision',
            name='our_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_our_decisions', to='reconciliation_app.transaction'),
        ),
    ]
