# Generated by Django 4.2.30 on 2026-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0003_manualdecision_external_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='manualdecision',
            name='unique_manual_transaction_pair',
        ),
        migrations.RemoveField(
            model_name='manualdecision',
            name='external_version',
        ),
        migrations.RemoveField(
            model_name='manualdecision',
            name='our_version',
        ),
        migrations.AddConstraint(
            model_name='manualdecision',
            constraint=models.UniqueConstraint(fields=('our_transaction', 'external_transaction'), name='unique_manual_transaction_pair'),
        ),
    ]
